repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        args: [--line-length=120]
